data<-read.table("household_power_consumption.txt", header=TRUE, sep = ";", colClasses = c( nrows = 2880, skip = 66636)
                 names(data)<-c("Date","Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
                 par(mar=c(2,4,2,1))
                     plot(data$Sub_metering_1, type = "l", axes = FALSE, ylab = "Energy sub metering")
                     points(data$Sub_metering_2, type = "l", col = "red")
                     points(data$Sub_metering_3, type = "l", col = "blue")
                     axis(1,c(0,1440,2880), c("Thu", "Fri", "Sat"))
                     axis(2,c(0,10,20,30))
                     legend(x=1950,y=35, col = c("black", "red", "blue"), legend = c ("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), pch = "_", box.col="white")
                     dev.copy(png, file = "plot3.png")
                     dev.off()